#!/usr/bin/env bash
# Install your load balancer

apt-get update
apt-get -y install haproxy

sed -i -e '$ afrontend http_front \n\tbind *:80 \
\tmode http \
\tdefault_backend http_rear \
\nbackend http_rear \
\tbalance		roundrobin \
\tserver 62718-web-01		54.197.113.231:80 check \
\tserver 62718-web-02		54.173.86.82:80 check' /etc/haproxy/haproxy.cfg

service haproxy restart